version: '3.8'
services:
  gemini:
    build: ./gemini
    ports:
      - 5000:5000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gemini

  nginx:
    build: ./nginx
    ports:
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    environment:
      - NGINX_HOST=d-art.site
      - NGINX_PORT=80
      - NGINX_SSL_PORT=443